### ISSUE TITLE
Edit Profile Not Saving

### ISSUE THREAD

**Issue by atitokor** [cyclosproject/cyclos4-ui#64] opened 2019-06-01 11:57 UTC
I just edited my end-user profile, and though the process completed smoothly, the change was not saved.

![1](https://user-images.githubusercontent.com/12918740/58748195-6fca2880-843a-11e9-8be6-4950dd66c9f1.png)

Thanks
Art

**Comment by luisfpg** [comment] 2019-06-03 11:42
@atitokor I couldn't reproduce it... Saving the profile works as expected.
What exactly isn't working?

**Comment by luisfpg** [comment] 2019-07-16 12:31
Closing this, as we cannot reproduce.

**Closed by luisfpg** 2019-07-16 12:31 UTC
Labels: bug
