### ISSUE TITLE
Can not registrate a user when no custom profile fields enabled

### ISSUE THREAD

**Issue by agonzalezcy** [cyclosproject/cyclos4-ui#133] opened 2019-06-26 17:06 UTC
Can not register a user in a group where no have custom profile field enable AtRegistration

How to reproduce:  Cyclos with a fresh develop db,

1. By Cyclos web, as admin, disable all AtRegistration field in System->Products->Bussiness->Edit->MyProfileFields

2. By UI, try to register a user (Guest registration) in Bussiness group (the Next button does nothing on push)

**Comment by agonzalezcy** [comment] 2019-06-26 18:30
check relation with #82 : Loading screen when trying to register an user as admin or public registration

**Comment by luisfpg** [comment] 2019-07-16 12:30
This no longer happens.
The server-side error is fixed in 4.12.1.

**Comment by agonzalezcy** [comment] 2019-07-17 18:03
The howToReproduce method still giving the same result (the Next button does not do anything)

**Comment by luisfpg** [comment] 2019-07-30 12:50
Still can't reproduce. Attached is a video. Is a blank development DB with all fields' 'at registration' unchecked.

![Issue 133](https://user-images.githubusercontent.com/1183737/62130479-785ea400-b2af-11e9-98ce-8fa5c5972ae2.gif)

**Comment by agonzalezcy** [comment] 2019-07-30 14:11
From a freshh develop DB: By Cyclos web, as admin, disable all AtRegistration field in System->Products->Bussiness->Edit->MyProfileFieldsy 
Then try to register a bussiness from UI
![Peek 2019-07-30 11-06](https://user-images.githubusercontent.com/50960346/62136590-ca58f700-b2ba-11e9-9f7f-75f4a0555246.gif)

**Closed** 2019-07-30 16:02 UTC
Labels: bug
